version: '3'
services:
  jenkins:
    environment:
      MIRROR_SOURCE: tencent
    image: hopher/jenkins:1.14.0
    container_name: my_jenkins
    build:
      context: .
      dockerfile: ./services/jenkins/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mounts the docker socket into the container
      - src:/home:rw
volumes:
  src:
    driver: local
    driver_opts:
      device: ${HOME}/src # docker 不支持相对路径
      o: bind